Enhanced Android TV Support
OpenLauncherTeam/openlauncher pull request #649
Opened 2021-02-27 09:14 UTC by nikiink

Add enhanced Android TV support:

- On some Android TV as the WallpaperManager is missing the app crashes at startup (now it does not crash)
- On first startup if on Android TV the desktop orientation is set to landscape as default
- On some Android TV as the WallpaperManager is missing, is not possible to set a system wallpaper, so i added an Android TV setting where to user can specify a wallpaper that set the wallpaper without using WallpaperManager.

(As soon as possible I will plan to add also DPAD support)

2021-08-01 12:25 UTC, gsantner commented
How stable is this? Do you have it in use for some time?

I don't have any real device Android TV to test.

2021-08-09 06:35 UTC, tonio-nucci commented
> 
> 
> How stable is this? Do you have it in use for some time?
> 
> I don't have any real device Android TV to test.

Yes, i use it on Android T9 TV box.

2021-11-22 21:07 UTC, gsantner requested changes
@tonio-nucci
I looked through the code (late but still). Here is my review.

When code quality gets OK, and you can assure it works as expected on TV - I plan to merge it.

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
> +            }
remove log

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
> +            }
remove log, remove debug code where there is still one

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
> +            // tonio-nucci (for DPAD/TV)
remove your name  (tonio-nucci) from comments please

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java
> +                     Log.i(this.getClass().getName(), "Page selected: " + i);
log

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/activity/SettingsActivity.java
> +                    break;
log

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/util/AppSettings.java
> +    ///
always {

}

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/util/Definitions.java
> +    public static final String DESKTOP_ORIENTATION_LANDSCAPE = "2";
unused?

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/widget/AppDrawerGrid.java
> +                                    v.setBackgroundColor(Color.argb(128, 255,255,255));
migrate to color resource, or reuse a existing java Color. or R.color. if available.

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/widget/AppItemView.java
> +            //tonio-nucci (for DPAD/TV)
tonio-nucci

2021-11-22 21:07 UTC, gsantner commented on app/src/main/java/com/benny/openlauncher/widget/GroupPopupView.java
> +        boolean focusSet = false;
maybe rename the var so it contains androidTV? as it's completley tv related

2021-11-22 21:07 UTC, gsantner commented on app/src/main/res/values/strings.xml
> +    <string name="pref_title__android_tv_wallpaper">Wallpaper</string>
Can be both in untranslatable

2022-01-03 18:34 UTC, gsantner commented
Without reaction I will close this stale pull request in 30 days of inactivity.

2022-04-18 11:16 UTC, gsantner commented
closing due inactivity

2022-04-18 11:16 UTC, closed without merging